FROM node:0.12

RUN mkdir /src

WORKDIR /src
ADD webapiserver/package.json /src/package.json
RUN npm install

ADD webapiserver/entrypoint.sh /entrypoint.sh
RUN chmod 755 /entrypoint.sh

EXPOSE 3000

CMD ["/entrypoint.sh"]
