FROM node:0.12

RUN mkdir /src

WORKDIR /src
ADD SPAclient/package.json /src/package.json
RUN npm install

ADD SPAclient/entrypoint.sh /entrypoint.sh
RUN chmod 755 /entrypoint.sh

CMD ["/entrypoint.sh"]
