FROM node:0.12

RUN mkdir /src

WORKDIR /src
ADD webserver/package.json /src/package.json
RUN npm install

ADD webserver/entrypoint.sh /entrypoint.sh
RUN chmod 755 /entrypoint.sh

EXPOSE 3000

CMD ["/entrypoint.sh"]
